### ISSUE TITLE
MAGEFILE_ENABLE_COLOR breaks mage-select

### ISSUE THREAD

**Issue by sheldonhull** [iwittkau/mage-select#4] opened 2022-02-28 18:43 UTC
I know there's not a lot of activity on this, but want to capture this issue as it caused me to stop using it for a while. 

If `MAGEFILE_ENABLE_COLOR=1 mage-select` is used, when the command is passed through it incorrectly escapes and won't work. When color is disabled it works fine. 

![2022-02-28-12 42 41-Code - Insiders-Pulumi dev yaml — ras  Dev Container Kubernetes - Minikube-in-Docker](https://user-images.githubusercontent.com/3526320/156039854-7c924bd8-20d5-4261-bf4f-bd5fbbb6daff.png)

![2022-02-28-12 43 02-Code - Insiders-Pulumi dev yaml — ras  Dev Container Kubernetes - Minikube-in-Docker](https://user-images.githubusercontent.com/3526320/156039893-aeea66bf-5720-4129-978b-35be03aaf062.png)

The end target for something like `mage go:doctor` ends up being `"\x1b[36mgo:doctor\x1b[0m"`.

**Comment by sheldonhull** [comment] 2022-02-28 18:57
The current solution in my shell is to simply create a function to use instead like this: 


```
if command -v mage &>/dev/null; then
  # Color breaks this tool, so disable for execution
  unalias mages  # Just in case this is already registered, make sure to unregister it
  function mages() { MAGEFILE_ENABLE_COLOR=0 mage-select }
  echo -e "➕ alias: mages";
fi
```

**Comment by iwittkau** [comment] 2022-02-28 19:07
Thank you for reporting this. You're right, it's quiet here because I'm currently not using `mage`.

But I think this is quite easy to fix. I have to reproduce this first ... hope to get back to you soon 🤞🏻

**Comment by iwittkau** [comment] 2022-02-28 22:34
Should be fixed in https://github.com/iwittkau/mage-select/releases/tag/v1.1.0

Happy maging 🧙‍♀️

If you still encounter problems, please re-open.

**Closed as completed by iwittkau** 2022-02-28 22:34 UTC

**Comment by sheldonhull** [comment] 2022-03-12 00:32
My hero!

**Comment by sheldonhull** [comment] 2022-03-12 00:33
Would love to hear what you are using if not mage now, back to bash scripts? I don't know if I could do that since I love Go so much ;-) Feel free to ping me on twitter for off-topic discussion if you like. It's linked on my profile page. cheers!

**Comment by mloskot** [comment] 2023-12-11 12:34
@iwittkau Thanks for the fix!

Since the fix https://github.com/iwittkau/mage-select/commit/f1a5309c40b2dce63b6565233e87c3a6470c4df9 resets `MAGEFILE_ENABLE_COLOR=0` instead of, perhaps, stripping colouring codes, `mage-select` may still fail for those who force `MAGEFILE_ENABLE_COLOR=1` in `init` function of their Magefiles.

Here is example how to correct the `init` function to make your Magefiles well-behaving for `mage-select`:

```go
func init() {
	var err error

	// Reset coloring only if not already enabled/disabled e.g. by mage-select
	disableColor := strings.TrimSpace(os.Getenv("MAGEFILE_ENABLE_COLOR"))
	if disableColor == "" {
		err = os.Setenv("MAGEFILE_ENABLE_COLOR", "1")
		if err != nil {
			panic(err)
		}
	}
...
}
```

@sheldonhull 
> Would love to hear what you are using if not mage now, back to bash scripts? I don't know if I could do that since I love Go so much ;-) 

I'd love to hear that too, for the same reasons. I have been using Mage as a general-purpose replacement for Bash scripting and I can't imagine myself going back to Bash. Sad to read @sheldonhull 's https://github.com/magefile/mage/issues/289#issuecomment-1823705608

**Comment by sheldonhull** [comment] 2023-12-11 14:42
Still using. It's stable and well featured so best option right now for me in Go. That said I hope to see maintenance pick back up someday.
No reason not to use it! 

I don't have any issues with color right now with the current fixes in place.
